
[tasks.switch]
run = "sudo nixos-rebuild switch -I nixos-config=./mine/configuration.nix --use-remote-sudo --upgrade"
depends_post = "restart"

[tasks.restart]
run = """
#!/usr/bin/env bash
echo "Do you want to restart the system? (y/n)"
read answer
if [ "$answer" == "y" ]; then
    echo "Restarting the system..."
    sudo systemctl reboot
else
    echo "System restart cancelled."
fi
"""


[tasks.test]
run = "sudo nixos-rebuild test -I nixos-config=./mine/configuration.nix --use-remote-sudo --upgrade" 

[tasks.fmt]
run = "nix fmt"

[tasks."hw"]
run = "sudo nixos-generate-config --show-hardware-config > hardware-configuration.nix"

[tasks.rebuild]
run = "sudo nixos-rebuild switch --flake ."


[tasks."channel:add"]
run = "sudo sudo nix-channel --add {{ arg(name='url') }} {{ arg(name='channel_name') }}"
depends_post = ["channel:list"]

[tasks."channel:list"]
run = "sudo nix-channel --list"

[tasks."channel:update"]
run = "sudo nix-channel --update"