
[tasks.switch]
run = "sudo nixos-rebuild switch -I nixos-config=./mine/configuration.nix --use-remote-sudo --upgrade"

[tasks.test]
run = "sudo nixos-rebuild test -I nixos-config=./mine/configuration.nix --use-remote-sudo --upgrade" 

[tasks.fmt]
run = "nix fmt"

[tasks."hw"]
run = "sudo nixos-generate-config --show-hardware-config > hardware-configuration.nix"

[tasks.rebuild]
run = "sudo nixos-rebuild switch --flake ."


[tasks."channel:add"]
run = "sudo sudo nix-channel --add {{ arg(name='url') }} {{ arg(name='channel_name')"
depends_post = ["channel:list"]

[tasks."channel:list"]
run = "sudo nix-channel --list"

[tasks."channel:update"]
run = "sudo nix-channel --update"