[tasks.test-zedsdk]
run = """
docker pull stereolabs/zed:5.0-gl-devel-cuda12.6-ubuntu24.04 
xhost +si:localuser:root 
docker run -it  --device nvidia.com/gpu=all --privileged -e DISPLAY -e XAUTHORITY \
  -v $XAUTHORITY:$XAUTHORITY \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v ./resoures:/usr/local/zed/resources \ 
  stereolabs/zed:5.0-gl-devel-cuda12.6-ubuntu24.04
"""
# https://www.perplexity.ai/search/docker-pull-stereolabs-zed-3-7-YSEo9r3vQJ6X2zVfQspXlw